### PR TITLE
[WIP] Support Multiple Versions

### PR DESCRIPTION
**Pull request by Techcable**
I just want your input  input on this before I merge as it is a _major_ change.
Benefits:
- Supports 1.8.3, 1.8, ProtocolHack, 1.7.10, and 1.7.9
- Adds skins 
- Allows me to effortlessly backport changes and fixes to previous Minecraft Versions.
- NPC fixes are shared across CombatTag, CombatTagReloaded and whoever else uses [NPCLib](https://github.com/TechzoneMC/NPCLib)

Downsides:
- Must use reflection to access NMS code
- NPCLib must be shaded into the plugin

### CODE REVIEW

**Comment by Outfenneced** [comment]
As you're the acting developer, I will default to you on this, but I must express my concern that I prefer CombatTag as a standalone that doesn't require much, if any, external unnecessary code. 

From what I can tell, this technically doesn't support multiple versions, if I understand it correctly, as if NPCLib or any of the reflections utilized in this pull request breaks, so will Combat Tag. Admittedly, it probably won't break every version, though.

**Comment by Techcable** [comment]
@Outfenneced 
NPCLib is actually shaded into the plugin using maven. NPCLib actually uses [maven abstraction to support multiple verisons](https://bukkit.org/threads/support-multiple-minecraft-versions-with-abstraction-maven.115810/) without reflection.
**Combat-Tag is already updated every version**, so it wouldn't really make a difference if I add more code to the reflection to support another version.

**Comment by Outfenneced** [comment]
Ok, I understand now. Sure, feel free to merge.

**Comment by Techcable** [comment]
Thanks for the approval, I'll be testing this some more to ensure it works correctly before I release.

**Pull request closed without merging**
